apiVersion: v1
kind: Service
metadata:
  name: splitwise-frontend
  labels:
    app: splitwise
    tier: frontend
spec:
  type: NodePort
  selector:
    app: splitwise
    tier: frontend
  ports:
    - port: 80       # cluster port (clients will use this)
      targetPort: 3000
      nodePort: 30001
      protocol: TCP
      name: http
